import type { LevelData } from './types.ts';

export const LEVELS: LevelData[] = [
  {
    id: 'tut-01',
    category: 'tutorial',
    title: 'First Hop',
    description: 'Drag the router between the client and server, then connect them.',
    nodes: [
      { id: 'client', type: 'source', label: 'Client', x: 100, y: 200 },
      { id: 'router', type: 'router', label: 'Router', x: 260, y: 200 },
      { id: 'server', type: 'target', label: 'Server', x: 420, y: 200 },
    ],
    edges: [],
    goal: {
      type: 'reachability',
      source: 'client',
      targets: ['server'],
      constraints: [{ type: 'maxHops', value: 2 }],
      budget: { newEdges: 2 },
    },
    palette: [{ type: 'edge', count: 2 }],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Glossary/Router',
    sourceTitle: 'MDN — Router',
  },
  {
    id: 'net-01',
    category: 'packet-routing',
    title: 'Shard Split',
    description: 'Route traffic around the failing shard to reach both replicas.',
    nodes: [
      { id: 'client', type: 'source', label: 'Client', x: 80, y: 220 },
      { id: 'lb', type: 'router', label: 'LB-A', x: 240, y: 120 },
      { id: 'shard1', type: 'service', label: 'Shard-1', x: 400, y: 80, health: 0.2 },
      { id: 'shard2', type: 'service', label: 'Shard-2', x: 400, y: 220, health: 1.0 },
      { id: 'shard3', type: 'service', label: 'Shard-3', x: 400, y: 360, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'client', to: 'lb', weight: 10 },
      { id: 'e2', from: 'lb', to: 'shard1', weight: 15 },
    ],
    goal: {
      type: 'reachability',
      source: 'client',
      targets: ['shard2', 'shard3'],
      constraints: [
        { type: 'maxLatency', value: 120 },
        { type: 'avoidNode', nodeId: 'shard1' },
      ],
      budget: { newEdges: 2, moves: 3 },
    },
    palette: [{ type: 'edge', count: 2 }],
    sourceUrl: 'https://sre.google/sre-book/load-balancing-frontend/',
    sourceTitle: 'Google SRE Book — Load Balancing',
  },
  {
    id: 'db-01',
    category: 'schema-repair',
    title: 'Orphan Orders',
    description: 'Reconnect the orders table to its customer without using the deprecated archive.',
    nodes: [
      { id: 'orders', type: 'database', label: 'Orders', x: 120, y: 200 },
      { id: 'archive', type: 'database', label: 'Archive', x: 320, y: 120, health: 0.0 },
      { id: 'customers', type: 'database', label: 'Customers', x: 320, y: 280, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'orders', to: 'archive', weight: 1 },
    ],
    goal: {
      type: 'reachability',
      source: 'orders',
      targets: ['customers'],
      constraints: [{ type: 'avoidNode', nodeId: 'archive' }],
      budget: { newEdges: 1, moves: 1 },
    },
    palette: [{ type: 'edge', count: 1 }],
    sourceUrl: 'https://en.wikipedia.org/wiki/Foreign_key',
    sourceTitle: 'Wikipedia — Foreign Key',
  },
  {
    id: 'git-01',
    category: 'merge-maze',
    title: 'Linearize History',
    description: 'Two feature branches merged into one commit. Rewire edges so history is a single linear chain — no commits deleted, just reordered.',
    nodes: [
      { id: 'root', type: 'commit', label: 'main~2', x: 80, y: 200 },
      { id: 'a', type: 'commit', label: 'feat-a', x: 220, y: 120 },
      { id: 'b', type: 'commit', label: 'feat-b', x: 220, y: 280 },
      { id: 'merge', type: 'commit', label: 'merge', x: 360, y: 200 },
      { id: 'tip', type: 'commit', label: 'main', x: 500, y: 200 },
    ],
    edges: [
      { id: 'e1', from: 'root', to: 'a', weight: 1 },
      { id: 'e2', from: 'root', to: 'b', weight: 1 },
      { id: 'e3', from: 'a', to: 'merge', weight: 1 },
      { id: 'e4', from: 'b', to: 'merge', weight: 1 },
      { id: 'e5', from: 'merge', to: 'tip', weight: 1 },
    ],
    goal: {
      type: 'linearize',
      source: 'root',
      targets: ['tip'],
      constraints: [],
      budget: { rewires: 2, moves: 2 },
    },
    palette: [],
    sourceUrl: 'https://git-scm.com/docs/git-rebase',
    sourceTitle: 'Git — git-rebase',
  },
  {
    id: 'dep-01',
    category: 'dependency-lock',
    title: 'Break the Cycle',
    description: 'Remove one edge to break the circular dependency between packages.',
    nodes: [
      { id: 'ui', type: 'package', label: '@app/ui', x: 200, y: 100 },
      { id: 'utils', type: 'package', label: '@app/utils', x: 400, y: 100 },
      { id: 'core', type: 'package', label: '@app/core', x: 300, y: 280 },
    ],
    edges: [
      { id: 'e1', from: 'ui', to: 'core', weight: 1 },
      { id: 'e2', from: 'core', to: 'utils', weight: 1 },
      { id: 'e3', from: 'utils', to: 'ui', weight: 1 },
    ],
    goal: {
      type: 'noCycle',
      source: 'ui',
      targets: ['core', 'utils'],
      constraints: [{ type: 'noCycle' }],
      budget: { deletes: 1, moves: 1 },
    },
    palette: [],
    sourceUrl: 'https://docs.npmjs.com/cli/v10/configuring-npm/folders',
    sourceTitle: 'npm — Folders',
  },
  {
    id: 'svc-01',
    category: 'api-orchestration',
    title: 'Failover Chain',
    description: 'Add a gateway and route around the unhealthy service while keeping latency under 130.',
    nodes: [
      { id: 'ingress', type: 'gateway', label: 'Ingress', x: 80, y: 220 },
      { id: 'auth', type: 'service', label: 'Auth', x: 240, y: 220, health: 0.3 },
      { id: 'payments', type: 'service', label: 'Payments', x: 420, y: 140, health: 1.0 },
      { id: 'fallback', type: 'service', label: 'Fallback', x: 420, y: 300, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'ingress', to: 'auth', weight: 10 },
      { id: 'e2', from: 'auth', to: 'payments', weight: 40 },
    ],
    goal: {
      type: 'reachability',
      source: 'ingress',
      targets: ['payments', 'fallback'],
      constraints: [{ type: 'maxLatency', value: 130 }],
      budget: { newEdges: 2, moves: 2 },
    },
    palette: [{ type: 'edge', count: 2 }],
    sourceUrl: 'https://microservices.io/patterns/reliability/circuitbreaker.html',
    sourceTitle: 'Microservices.io — Circuit Breaker',
  },
  // === NEW LEVELS ===
  {
    id: 'net-02',
    category: 'packet-routing',
    title: 'Bottleneck Break',
    description: 'Two clients share a single overloaded router. Add a second path so latency stays under 80.',
    nodes: [
      { id: 'c1', type: 'source', label: 'Client-A', x: 60, y: 120 },
      { id: 'c2', type: 'source', label: 'Client-B', x: 60, y: 320 },
      { id: 'r1', type: 'router', label: 'RTR-1', x: 240, y: 220, health: 0.4 },
      { id: 'svc', type: 'service', label: 'API', x: 440, y: 120, health: 1.0 },
      { id: 'db', type: 'database', label: 'DB', x: 440, y: 320, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'c1', to: 'r1', weight: 20 },
      { id: 'e2', from: 'c2', to: 'r1', weight: 20 },
      { id: 'e3', from: 'r1', to: 'svc', weight: 30 },
      { id: 'e4', from: 'r1', to: 'db', weight: 35 },
    ],
    goal: {
      type: 'reachability',
      source: 'c1',
      targets: ['svc', 'db'],
      constraints: [
        { type: 'maxLatency', value: 80 },
        { type: 'avoidNode', nodeId: 'r1' },
      ],
      budget: { newEdges: 3, moves: 2 },
    },
    palette: [{ type: 'edge', count: 3 }],
    sourceUrl: 'https://blog.cloudflare.com/the-state-of-the-art-of-bgp-routing/',
    sourceTitle: 'Cloudflare — BGP Routing',
  },
  {
    id: 'net-03',
    category: 'packet-routing',
    title: 'Mesh Relay',
    description: 'A 7-node mesh with one failing link. Re-route across the mesh to reach all three services.',
    nodes: [
      { id: 'src', type: 'source', label: 'Edge', x: 60, y: 240 },
      { id: 'r1', type: 'router', label: 'R1', x: 180, y: 120 },
      { id: 'r2', type: 'router', label: 'R2', x: 180, y: 360 },
      { id: 'r3', type: 'router', label: 'R3', x: 340, y: 120, health: 0.1 },
      { id: 'r4', type: 'router', label: 'R4', x: 340, y: 360 },
      { id: 's1', type: 'service', label: 'SVC-A', x: 500, y: 120 },
      { id: 's2', type: 'service', label: 'SVC-B', x: 500, y: 240 },
      { id: 's3', type: 'service', label: 'SVC-C', x: 500, y: 360 },
    ],
    edges: [
      { id: 'e1', from: 'src', to: 'r1', weight: 10 },
      { id: 'e2', from: 'src', to: 'r2', weight: 10 },
      { id: 'e3', from: 'r1', to: 'r3', weight: 15 },
      { id: 'e4', from: 'r2', to: 'r4', weight: 15 },
      { id: 'e5', from: 'r3', to: 's1', weight: 10 },
      { id: 'e6', from: 'r3', to: 's2', weight: 20 },
      { id: 'e7', from: 'r4', to: 's3', weight: 10 },
    ],
    goal: {
      type: 'reachability',
      source: 'src',
      targets: ['s1', 's2', 's3'],
      constraints: [
        { type: 'maxLatency', value: 55 },
        { type: 'avoidNode', nodeId: 'r3' },
      ],
      budget: { newEdges: 3, moves: 1 },
    },
    palette: [{ type: 'edge', count: 3 }],
    sourceUrl: 'https://www.cloudflare.com/learning/network-layer/what-is-a-mesh-network/',
    sourceTitle: 'Cloudflare — Mesh Networks',
  },
  {
    id: 'net-04',
    category: 'packet-routing',
    title: 'Capacity Crunch',
    description: 'A core router can only handle 2 connections. Reroute traffic so no node exceeds its bandwidth limit.',
    nodes: [
      { id: 'src', type: 'source', label: 'Edge', x: 60, y: 220 },
      { id: 'r1', type: 'router', label: 'Core-RTR', x: 220, y: 220, capacity: 2 },
      { id: 'r2', type: 'router', label: 'Edge-RTR', x: 220, y: 80 },
      { id: 's1', type: 'service', label: 'API', x: 400, y: 80, health: 1.0 },
      { id: 's2', type: 'service', label: 'Auth', x: 400, y: 220, health: 1.0 },
      { id: 's3', type: 'service', label: 'DB', x: 400, y: 360, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'src', to: 'r1', weight: 10 },
      { id: 'e2', from: 'r1', to: 's1', weight: 15 },
      { id: 'e3', from: 'r1', to: 's2', weight: 15 },
      { id: 'e4', from: 'r1', to: 's3', weight: 20 },
    ],
    goal: {
      type: 'reachability',
      source: 'src',
      targets: ['s1', 's2', 's3'],
      constraints: [
        { type: 'maxLatency', value: 60 },
        { type: 'maxCapacity', nodeId: 'r1', value: 2 },
      ],
      budget: { newEdges: 3, moves: 1 },
    },
    palette: [{ type: 'edge', count: 3 }],
    sourceUrl: 'https://www.cloudflare.com/learning/network-layer/what-is-bandwidth/',
    sourceTitle: 'Cloudflare — Bandwidth',
  },
  {
    id: 'db-02',
    category: 'schema-repair',
    title: 'Double Join',
    description: 'Orders point to the wrong table. Reroute through the join table to reach both dimensions.',
    nodes: [
      { id: 'orders', type: 'database', label: 'Orders', x: 80, y: 220 },
      { id: 'legacy', type: 'database', label: 'Legacy-Users', x: 260, y: 100, health: 0.0 },
      { id: 'join', type: 'database', label: 'Order-Items', x: 260, y: 220 },
      { id: 'users', type: 'database', label: 'Users', x: 440, y: 100, health: 1.0 },
      { id: 'products', type: 'database', label: 'Products', x: 440, y: 340, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'orders', to: 'legacy', weight: 1 },
      { id: 'e2', from: 'legacy', to: 'users', weight: 1 },
    ],
    goal: {
      type: 'reachability',
      source: 'orders',
      targets: ['users', 'products'],
      constraints: [{ type: 'avoidNode', nodeId: 'legacy' }],
      budget: { newEdges: 2, moves: 1 },
    },
    palette: [{ type: 'edge', count: 2 }],
    sourceUrl: 'https://en.wikipedia.org/wiki/Join_(SQL)',
    sourceTitle: 'Wikipedia — SQL Join',
  },
  {
    id: 'db-03',
    category: 'schema-repair',
    title: 'Shard Bridge',
    description: 'Three shards are disconnected. Bridge them with minimal edges so all are reachable.',
    nodes: [
      { id: 'gateway', type: 'gateway', label: 'API-GW', x: 80, y: 220 },
      { id: 'shard-a', type: 'database', label: 'Shard-A', x: 260, y: 100 },
      { id: 'shard-b', type: 'database', label: 'Shard-B', x: 260, y: 220 },
      { id: 'shard-c', type: 'database', label: 'Shard-C', x: 260, y: 340 },
      { id: 'cache', type: 'cache', label: 'Redis', x: 440, y: 100, health: 1.0 },
      { id: 'report', type: 'service', label: 'Report-SVC', x: 440, y: 340, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'gateway', to: 'shard-b', weight: 5 },
    ],
    goal: {
      type: 'reachability',
      source: 'gateway',
      targets: ['shard-a', 'shard-c', 'cache', 'report'],
      constraints: [{ type: 'maxLatency', value: 30 }],
      budget: { newEdges: 4, moves: 2 },
    },
    palette: [{ type: 'edge', count: 4 }],
    sourceUrl: 'https://en.wikipedia.org/wiki/Shard_(database_architecture)',
    sourceTitle: 'Wikipedia — Database Sharding',
  },
  {
    id: 'db-04',
    category: 'schema-repair',
    title: 'Cascading Cut',
    description: 'A legacy table is being retired. Disconnect it without orphaning any dependent tables.',
    nodes: [
      { id: 'app', type: 'gateway', label: 'App', x: 60, y: 220 },
      { id: 'legacy', type: 'database', label: 'Legacy-DB', x: 220, y: 100, health: 0.0 },
      { id: 'orders', type: 'database', label: 'Orders', x: 220, y: 220 },
      { id: 'items', type: 'database', label: 'Items', x: 220, y: 340 },
      { id: 'new-db', type: 'database', label: 'New-DB', x: 400, y: 220, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'app', to: 'legacy', weight: 5 },
      { id: 'e2', from: 'legacy', to: 'orders', weight: 1 },
      { id: 'e3', from: 'legacy', to: 'items', weight: 1 },
    ],
    goal: {
      type: 'reachability',
      source: 'app',
      targets: ['orders', 'items', 'new-db'],
      constraints: [
        { type: 'avoidNode', nodeId: 'legacy' },
        { type: 'noOrphans' },
      ],
      budget: { newEdges: 3, moves: 1 },
    },
    palette: [{ type: 'edge', count: 3 }],
    sourceUrl: 'https://en.wikipedia.org/wiki/Cascading_delete',
    sourceTitle: 'Wikipedia — Cascading Delete',
  },
  {
    id: 'git-02',
    category: 'merge-maze',
    title: 'Squash Branch',
    description: 'Three feature commits feed a merge commit. Rewire into a single linear chain — rebase, don\'t delete.',
    nodes: [
      { id: 'root', type: 'commit', label: 'main~3', x: 60, y: 220 },
      { id: 'a', type: 'commit', label: 'feat-a', x: 200, y: 100 },
      { id: 'b', type: 'commit', label: 'feat-b', x: 200, y: 220 },
      { id: 'c', type: 'commit', label: 'feat-c', x: 200, y: 340 },
      { id: 'merge', type: 'commit', label: 'merge', x: 360, y: 220 },
      { id: 'tip', type: 'commit', label: 'main', x: 500, y: 220 },
    ],
    edges: [
      { id: 'e1', from: 'root', to: 'a', weight: 1 },
      { id: 'e2', from: 'root', to: 'b', weight: 1 },
      { id: 'e3', from: 'root', to: 'c', weight: 1 },
      { id: 'e4', from: 'a', to: 'merge', weight: 1 },
      { id: 'e5', from: 'b', to: 'merge', weight: 1 },
      { id: 'e6', from: 'c', to: 'merge', weight: 1 },
      { id: 'e7', from: 'merge', to: 'tip', weight: 1 },
    ],
    goal: {
      type: 'linearize',
      source: 'root',
      targets: ['tip'],
      constraints: [],
      budget: { rewires: 4, moves: 2 },
    },
    palette: [],
    sourceUrl: 'https://git-scm.com/docs/git-rebase',
    sourceTitle: 'Git — Interactive Rebase',
  },
  {
    id: 'dep-02',
    category: 'dependency-lock',
    title: 'Diamond Dependency',
    description: 'App depends on two libs that both depend on different versions of core. Break the version conflict.',
    nodes: [
      { id: 'app', type: 'package', label: 'app', x: 100, y: 220 },
      { id: 'lib-a', type: 'package', label: 'lib-a@2', x: 260, y: 120 },
      { id: 'lib-b', type: 'package', label: 'lib-b@3', x: 260, y: 320 },
      { id: 'core-1', type: 'package', label: 'core@1', x: 440, y: 120, health: 0.2 },
      { id: 'core-2', type: 'package', label: 'core@2', x: 440, y: 320, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'app', to: 'lib-a', weight: 1 },
      { id: 'e2', from: 'app', to: 'lib-b', weight: 1 },
      { id: 'e3', from: 'lib-a', to: 'core-1', weight: 1 },
      { id: 'e4', from: 'lib-b', to: 'core-2', weight: 1 },
    ],
    goal: {
      type: 'reachability',
      source: 'app',
      targets: ['core-2'],
      constraints: [{ type: 'avoidNode', nodeId: 'core-1' }],
      budget: { newEdges: 1, deletes: 1, moves: 1 },
    },
    palette: [{ type: 'edge', count: 1 }],
    sourceUrl: 'https://docs.npmjs.com/cli/v10/commands/npm-ls',
    sourceTitle: 'npm — npm-ls',
  },
  {
    id: 'dep-03',
    category: 'dependency-lock',
    title: 'Peer Pressure',
    description: 'lib-a requires core@2 but pulls core@1. Rewire to the correct version before the build breaks.',
    nodes: [
      { id: 'app', type: 'package', label: 'app', x: 60, y: 220 },
      { id: 'lib-a', type: 'package', label: 'lib-a', x: 220, y: 120 },
      { id: 'lib-b', type: 'package', label: 'lib-b', x: 220, y: 320 },
      { id: 'core-1', type: 'package', label: 'core@1', x: 400, y: 120, health: 0.1 },
      { id: 'core-2', type: 'package', label: 'core@2', x: 400, y: 320, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'app', to: 'lib-a', weight: 1 },
      { id: 'e2', from: 'app', to: 'lib-b', weight: 1 },
      { id: 'e3', from: 'lib-a', to: 'core-1', weight: 1 },
      { id: 'e4', from: 'lib-b', to: 'core-2', weight: 1 },
    ],
    goal: {
      type: 'reachability',
      source: 'app',
      targets: ['core-2'],
      constraints: [
        { type: 'avoidNode', nodeId: 'core-1' },
        { type: 'versionRequires', requiresNode: 'core-1', requiresVersion: 'core@2' },
      ],
      budget: { newEdges: 1, deletes: 1, moves: 1 },
    },
    palette: [{ type: 'edge', count: 1 }],
    sourceUrl: 'https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependencies',
    sourceTitle: 'npm — peerDependencies',
  },
  {
    id: 'svc-02',
    category: 'api-orchestration',
    title: 'Cascade Failure',
    description: 'Auth is down and blocks the whole chain. Bypass it to reach billing and notifications.',
    nodes: [
      { id: 'gw', type: 'gateway', label: 'Gateway', x: 60, y: 220 },
      { id: 'auth', type: 'service', label: 'Auth', x: 200, y: 220, health: 0.1 },
      { id: 'orders', type: 'service', label: 'Orders', x: 360, y: 100, health: 1.0 },
      { id: 'billing', type: 'service', label: 'Billing', x: 520, y: 100, health: 1.0 },
      { id: 'notify', type: 'service', label: 'Notify', x: 520, y: 300, health: 1.0 },
      { id: 'queue', type: 'cache', label: 'Queue', x: 360, y: 340, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'gw', to: 'auth', weight: 15 },
      { id: 'e2', from: 'auth', to: 'orders', weight: 20 },
      { id: 'e3', from: 'orders', to: 'billing', weight: 10 },
      { id: 'e4', from: 'auth', to: 'notify', weight: 25 },
    ],
    goal: {
      type: 'reachability',
      source: 'gw',
      targets: ['billing', 'notify'],
      constraints: [
        { type: 'maxLatency', value: 70 },
        { type: 'avoidNode', nodeId: 'auth' },
      ],
      budget: { newEdges: 3, moves: 2 },
    },
    palette: [{ type: 'edge', count: 3 }],
    sourceUrl: 'https://microservices.io/patterns/reliability/circuitbreaker.html',
    sourceTitle: 'Microservices.io — Circuit Breaker',
  },
  {
    id: 'svc-03',
    category: 'api-orchestration',
    title: 'Retry Budget',
    description: 'A flaky payment gateway must be reachable with latency under 100. Route through the cache to avoid the slow path.',
    nodes: [
      { id: 'gw', type: 'gateway', label: 'API-GW', x: 60, y: 220 },
      { id: 'auth', type: 'service', label: 'Auth', x: 200, y: 100, health: 1.0 },
      { id: 'pay-gw', type: 'service', label: 'PayGW', x: 200, y: 340, health: 0.3 },
      { id: 'cache', type: 'cache', label: 'Redis', x: 360, y: 220, health: 1.0 },
      { id: 'pay', type: 'service', label: 'Payments', x: 520, y: 100, health: 1.0 },
      { id: 'ledger', type: 'database', label: 'Ledger', x: 520, y: 340, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'gw', to: 'auth', weight: 10 },
      { id: 'e2', from: 'gw', to: 'pay-gw', weight: 15 },
      { id: 'e3', from: 'auth', to: 'pay', weight: 20 },
      { id: 'e4', from: 'pay-gw', to: 'ledger', weight: 50 },
    ],
    goal: {
      type: 'reachability',
      source: 'gw',
      targets: ['pay', 'ledger'],
      constraints: [
        { type: 'maxLatency', value: 100 },
        { type: 'avoidNode', nodeId: 'pay-gw' },
      ],
      budget: { newEdges: 3, moves: 1 },
    },
    palette: [{ type: 'edge', count: 3 }],
    sourceUrl: 'https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/retry-pattern.html',
    sourceTitle: 'AWS — Retry Pattern',
  },
  {
    id: 'svc-04',
    category: 'api-orchestration',
    title: 'Retry Relay',
    description: 'A flaky payment service has high latency. Place a retry node in the path to halve the effective latency.',
    nodes: [
      { id: 'gw', type: 'gateway', label: 'Gateway', x: 60, y: 220 },
      { id: 'auth', type: 'service', label: 'Auth', x: 200, y: 100, health: 1.0 },
      { id: 'pay', type: 'service', label: 'Payments', x: 400, y: 100, health: 0.3 },
      { id: 'retry', type: 'retry', label: 'Retry', x: 200, y: 340 },
      { id: 'ledger', type: 'database', label: 'Ledger', x: 400, y: 340, health: 1.0 },
    ],
    edges: [
      { id: 'e1', from: 'gw', to: 'auth', weight: 15 },
      { id: 'e2', from: 'auth', to: 'pay', weight: 80 },
      { id: 'e3', from: 'gw', to: 'ledger', weight: 60 },
    ],
    goal: {
      type: 'reachability',
      source: 'gw',
      targets: ['pay', 'ledger'],
      constraints: [{ type: 'maxLatency', value: 60 }],
      budget: { newEdges: 3, moves: 1 },
    },
    palette: [{ type: 'edge', count: 3 }],
    sourceUrl: 'https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/retry-pattern.html',
    sourceTitle: 'AWS — Retry with Backoff',
  },
];

export function getLevel(id: string): LevelData | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function firstLevelId(): string {
  return LEVELS[0].id;
}

export function nextLevelId(current: string): string | null {
  const idx = LEVELS.findIndex((l) => l.id === current);
  return LEVELS[idx + 1]?.id ?? null;
}
